[package]
name = "roa-pg"
version = "0.5.1"
authors = ["Hexilee <i@hexilee.me>"]
edition = "2018"
license = "MIT"
readme = "./README.md"
repository = "https://github.com/Hexilee/roa"
documentation = "https://docs.rs/roa-pg"
homepage = "https://github.com/Hexilee/roa/wiki"
description = "tokio-postgres integration with roa framework"
keywords = ["http", "web", "framework", "database"]
categories = ["database"]

[package.metadata.docs.rs]
features = ["docs"]
rustdoc-args = ["--cfg", "feature=\"docs\""]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.3"
futures = "0.3.4"
roa = { path = "../roa", version = "0.5.0", default-features = false }
tokio-postgres = { version = "0.5.2", default-features = false }
tokio = "0.2.13"
async-std = "1.5"
tokio-rustls = { version = "0.13.0", features = ["unstable"] }
webpki = "0.21.2"

[dev-dependencies]
async-std = { version = "1.5", features = ["attributes"] }
roa = { path = "../roa", version = "0.5.0" }

[features]
docs = ["roa/docs"]
with-bit-vec-0_6 = ["tokio-postgres/with-bit-vec-0_6"]
with-chrono-0_4 = ["tokio-postgres/with-chrono-0_4"]
with-eui48-0_4 = ["tokio-postgres/with-eui48-0_4"]
with-geo-types-0_4 = ["tokio-postgres/with-geo-types-0_4"]
with-serde_json-1 = ["tokio-postgres/with-serde_json-1"]
with-uuid-0_8 = ["tokio-postgres/with-uuid-0_8"]
with-time-0_2 = ["tokio-postgres/with-time-0_2"]

