on: [push, pull_request]
name: Stable Test
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.60.0
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Check all
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --features "roa/full"
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - 1.60.0
    steps:
      - name: Install libsqlite3-dev
        run: |
          sudo apt-get update
          sudo apt-get -y install libsqlite3-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Run all tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --features "roa/full" --no-fail-fast
        
